spring:
  application:
    name: user-center
  # DataSource Config
  datasource:
    url: jdbc:mysql://localhost:3306/user_center
    driver-class-name: com.mysql.jdbc.Driver
    name: root
    password: 1234
server:
  port: 8080
